# Site settings
title: "BSIA, April 21-22"
email: john.mclevey@uwaterloo.ca
description: "A workshop at the Balsillie School of International Affairs"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links

people:
- name: John McLevey
  pic: john
  position: University of Waterloo
  social:
    - title: link
      url: "http://www.johnmclevey.com" 
    - title: twitter
      url: https://twitter.com/johnmclevey


- name: Vanessa Schweizer
  pic: vanessa
  position: University of Waterloo
  social:
    - title: link
      url: "https://uwaterloo.ca/knowledge-integration/faculty-schweizer"
    - title: twitter
      url: https://twitter.com/vschweizer

- name: Mark Stoddart
  pic: mark
  position: Memorial University
  social:
    - title: link
      url: "http://www.mun.ca/soc/faculty/faculty-profiles/mark-c-j-stoddart.php"
    - title: twitter
      url: https://twitter.com/mcjs13

- name: Tahnee Prior
  pic: tahnee
  position: "BSIA, University of Waterloo"
  social:
    - title: link
      url: "http://www.tahnee.is"
    - title: twitter
      url: https://twitter.com/tahnsta

# Build settings
markdown: kramdown
permalink: pretty